# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: YongAnFrame Dev CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v4
    
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Generate NuGet packages
      run: dotnet pack

    - name: Upload NuGet package
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: YongAnFrame.*.nupkg
