# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: YongAnFrame Dev CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v4
    
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v3

    - name: Restore NuGet packages
      run: nuget restore YongAnFrame.sln
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
